version: '3.7'

services:
  mysqlDb:
    container_name: nlw-sports
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: nlw
      MYSQL_USER: kaell
      MYSQL_PASSWORD: 123
    ports:
      - '9906:3306'
    volumes:
      - "./db:/var/lib/mysql"
    networks:
      - production-network
networks:
    production-network:
        driver: bridge